### ISSUE TITLE
Update API endpoints

### ISSUE THREAD

**Issue by brnsmns13** [ISUBikeShare/WebInterface#20]
Most of our API endpoints need to be updated to follow basic (REST rules)[http://en.wikipedia.org/wiki/Representational_state_transfer]. All models in the database will require only a single endpoint to handle all interactions. For example, the ```/dock``` endoint will handle creation, updates, and queries for all requests depending on the HTTP method.

**Comment by seancavanaugh** [comment]
Completed per: https://github.com/ISUBikeShare/WebInterface/pull/36
