### ISSUE TITLE
A user is allowed to check out multiple bikes

### ISSUE THREAD

**Issue by brnsmns13** [ISUBikeShare/WebInterface#28]
Multiple checkout requests with the same card are successful. They should fail after the first checkout and a user should only be able to checkout one bike at a time.

@jcurtiss @seancavanaugh

**Comment by jcurtiss** [comment]
This one is on me, forgot to deploy

**Comment by jcurtiss** [comment]
@brnsmns13 it is now deployed, this should no longer be an issue
