### ISSUE TITLE
500 Error on checkin/checkout

### ISSUE THREAD

**Issue by brnsmns13** [ISUBikeShare/WebInterface#30]
When trying to check in a bike with id of "6A0049EE509D" the server returns a 500 error. This needs to register as a valid bike id.

We need this fixed before the demo tomorrow.

@jcurtiss @seancavanaugh @daotoo

**Comment by seancavanaugh** [comment]
@brnsmns13 BikeID's were supposed to come in as a number. I can fix this.

**Comment by seancavanaugh** [comment]
This is fixed now in master. Just need @jcurtiss to deploy now.

**Comment by seancavanaugh** [comment]
@brnsmns13 I'm going to assume this is no longer an issue since we haven't gotten a response back. Feel free to reopen if it.
