### ISSUE TITLE
Docks page issues

### ISSUE THREAD

**Issue by daotoo** [ISUBikeShare/WebInterface#31]
![screen shot 2015-03-29 at 3 45 38 pm](https://cloud.githubusercontent.com/assets/5438937/6887625/be900542-d62a-11e4-9a7c-d5031a0e38ea.png)

When Docks and Bikes are created, on the Docks page, it looks like the BikeIDs and DockIDs are switched in some cases. 

In the image above, 6A.... is a BikeID but it listed as a Dock.

**Comment by daotoo** [comment]
@jcurtiss

**Comment by jcurtiss** [comment]
Looks like the database is incorrect. In the bikes, the bikeIds start with '6A' and the dockId is just s long string of numbers. In the docks, the dockId starts with 6A and the bikeId is the long string of numbers

**Comment by daotoo** [comment]
Fixed the issue in the database and this is no longer a problem. Closing.
