### ISSUE TITLE
Create unit tests for code

### ISSUE THREAD

**Issue by seancavanaugh** [ISUBikeShare/WebInterface#33]

**Comment by seancavanaugh** [comment]
https://thewayofcode.wordpress.com/2013/04/21/how-to-build-and-test-rest-api-with-nodejs-express-mocha/

https://strongloop.com/strongblog/how-to-test-an-api-with-node-js/

**Comment by seancavanaugh** [comment]
For a working example, look at https://github.com/ISUBikeShare/WebInterface/pull/37

**Comment by daotoo** [comment]
#40
