### ISSUE TITLE
Need rest endpoints to edit bikes and docks

### ISSUE THREAD

**Issue by jcurtiss** [ISUBikeShare/WebInterface#34]
I need an edit bike endpoint that takes a bike id, dock id, cardString (if that is a thing anymore?), state, and an isDamaged property. It should find the bike with the bike id in the database, then update that entity with the rest of the properties sent.

Same for the edit dock endpoint, but that will take a dock id, location, bike id, and status.

@daotoo @seancavanaugh

**Comment by seancavanaugh** [comment]
@jcurtiss  This has been done in this PR: https://github.com/ISUBikeShare/WebInterface/pull/36
